
#----------  Train and Test BTSA-MAML2 Cifar -----------------------
# python train_btsamaml2.py --dataset cifar100 --metatrain_iterations 60000 --meta_batch_size 4 --update_batch_size 1 --update_lr 0.01 --num_updates 5 --num_classes 5 --logdir logs/2maml_cifar5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_cifar5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset cifar100 --metatrain_iterations 60000 --meta_batch_size 4 --update_batch_size 5 --update_lr 0.01 --num_updates 5 --num_classes 5 --logdir logs/2maml_cifar5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_cifar5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset cifar100 --metatrain_iterations 60000 --meta_batch_size 4 --update_batch_size 1 --update_lr 0.01 --num_updates 5 --num_classes 10 --logdir logs/2maml_cifar5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_cifar5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset cifar100 --metatrain_iterations 60000 --meta_batch_size 4 --update_batch_size 5 --update_lr 0.01 --num_updates 5 --num_classes 10 --logdir logs/2maml_cifar5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_cifar5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4


#----------  Train and Test BTSA-MAML2 TieredImage -----------------------
# python train_btsamaml2.py --dataset tiered --metatrain_iterations 80000 --meta_batch_size 4 --update_batch_size 1 --update_lr 0.01 --num_updates 5 --num_classes 5 --logdir logs/2maml_tiered5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_tiered5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset tiered --metatrain_iterations 80000 --meta_batch_size 4 --update_batch_size 5 --update_lr 0.01 --num_updates 5 --num_classes 5 --logdir logs/2maml_tiered5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_tiered5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset tiered --metatrain_iterations 80000 --meta_batch_size 4 --update_batch_size 1 --update_lr 0.01 --num_updates 5 --num_classes 10 --logdir logs/2maml_tiered5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_tiered5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4
# python train_btsamaml2.py --dataset tiered --metatrain_iterations 80000 --meta_batch_size 4 --update_batch_size 5 --update_lr 0.01 --num_updates 5 --num_classes 10 --logdir logs/2maml_tiered5w1s --num_filters 32 --max_pool=True --num_test_tasks 600  --logdir=logs/2tsa_maml_cifar5w1s --premaml logs/maml_tiered5w1s/bestmodel  --num_groups 5 --cosann=True --meta_lr=5e-4